[package]
name = "rsytup"
version = "0.4.0"
edition = "2024"
repository = "https://github.com/bedroombuilds/rsytup/"
license = "GPL-3.0-or-later"
keywords = ["video", "youtube"]
categories = ["command-line-utilities", "multimedia"]

[dependencies]
anyhow = "1.0"
conv = "0.3.3"
env_logger = "0.11.11"
google-youtube3 = "7.0.0"
image = "0.25.10"
imageproc = "0.27.0"
mime = "0.3.17"
serde = "1.0"
clap = { version = "4.6", features = ["derive"] }
strum = { version = "0.28.0", features = ["derive", "strum_macros"], default-features = false  }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "io-util", "macros", "fs"] }
webbrowser = "1.2"
ab_glyph = "0.2.32"
chrono = { version = "0.4.45", default-features = false }
serde_json = "1.0.151"
futures-util = { version = "0.3", default-features = false, features = ["alloc"]}
